export class Genre {
    constructor (
        name?: String,
        wiki?: String,
        parent?: String,
        bandcamp?: String,
        lastfm?: String,
        spotify?: String,
    ) {}
}

const genres: Genre[] = [
    { name: 'folk', parent: 'other', wiki: '', lastfm: 'https://www.last.fm/tag/folk' },
    { name: 'alternative', parent: 'other', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/alternative'},
    { name: 'ambient', parent: 'experimental', wiki: '', lastfm: 'https://www.last.fm/tag/ambient' },
    { name: 'post-rock', parent: 'experimental', wiki: '', lastfm: 'https://www.last.fm/tag/post-rock' },
    { name: 'lowercase', parent: 'experimental', wiki: '', lastfm: 'https://www.last.fm/tag/lowercase' },

    { name: 'pop', parent: 'pop', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/pop'},
    { name: 'new-wave', parent: 'pop', wiki: '', lastfm: 'https://www.last.fm/tag/new-wave' },

    { name: 'hardcore', parent: 'hardcore', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/hardcore'},
    { name: 'post-hardcore', parent: 'hardcore',  wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/post-hardcore'},
    { name: 'slam', parent: 'hardcore', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/slam'},
    { name: 'grind-core', parent: 'metal', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/grindcore'},
    { name: 'porno-grind', parent: 'metal', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/porno-grind'},
    { name: 'hardcore-punk', parent: 'punk', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/hardcore-punk'},
    { name: 'death-core', parent: 'hardcore', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/deathcore'},
    { name: 'indie', parent: 'pop', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/indie'},
    { name: 'indie-folk', parent: 'pop', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/indie-folk'},
    { name: 'indie-pop', parent: 'pop', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/indie-pop'},
    { name: 'math-rock', parent: 'experimental', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/math-rock'},
    { name: 'experimental', parent: 'experimental', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/experimental'},
    { name: 'spoken-word', parent: 'experimental', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/spoken-word'},
    { name: 'house', parent: 'experimental', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/house'},
    { name: 'trip-hop', parent: 'experimental', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/trip-hop'},
    { name: 'hip-hop', parent: 'other', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/hip-hop'},
    { name: 'pop-core', parent: 'other', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/pop-core'},
    { name: 'sadboi', parent: 'other', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/sadboi'},
    { name: 'power-violence', parent: 'hardcore', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/power'},
    { name: 'emo-violence', parent: 'hardcore', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/emo'},
    { name: 'skramz', parent: 'experimental', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/skramz'},
    { name: 'screamo', parent: 'experimental', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/screamo'},
    { name: 'metal', parent: 'metal',  wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/metal'},
    { name: 'nu-metal', parent: 'metal', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/nu-metal'},
    { name: 'metal-core', parent: 'hardcore', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/metal-core'},
    { name: 'death-metal', parent: 'metal', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/death-core'},
    { name: 'doom-metal', parent: 'metal', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/doom'},
    { name: 'stoner-metal', parent: 'metal', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/stoner-metal'},
    { name: 'emo', wiki: '', parent: 'other', spotify: '', lastfm: 'https://www.last.fm/tag/emo'},
    { name: 'emo-revival', parent: 'punk', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/emo-revival'},
    { name: 'emo-acoustic',  parent: 'pop', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/emo-acoustic'},
    { name: 'twinkle-emo', parent: 'experimental', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/twinkle-emo'},
    { name: 'screamo', parent: 'hardcore', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/screamo'},
    { name: 'skramz', parent: 'hardcore', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/skramz'},
    { name: 'pop-punk', parent: 'pop-punk', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/pop-punk'},
    { name: 'ska', parent: 'ska', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/ska'},

    { name: 'punk', parent: 'punk', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/punk'},
    { name: 'post-punk', parent: 'punk', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/post-punk'},
    { name: 'noise', parent: 'experimental', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/noise'},
    { name: 'noise-metal', parent: 'metal', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/noise-metal'},
    { name: 'industrial', parent: 'experimental', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/industrial'},
    { name: 'industrial-metal', parent: 'metal', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/industrial-metal'},
    { name: 'electronic', parent: 'pop', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/electronic'},
    { name: 'electro-pop', parent: 'pop', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/electro-pop'},
    { name: 'ebm', parent: 'other', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/ebm'},
    { name: 'trap', parent: 'other', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/trap'},
    { name: 'dubstep', parent: 'other', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/dubstep'},
    { name: 'witch house', parent: 'experimental', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/witch+house'},
    { name: 'grime', parent: 'other', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/grime'},
    { name: 'darkwave', parent: 'other', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/darkwave'},
    { name: 'synthpop', parent: 'pop', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/synthpop'},
    { name: 'garage-rock', parent: 'pop', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/garage-rock'},
    { name: 'jazz', parent: 'experimental', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/jazz'},
    { name: 'acid-jazz', parent: 'experimental', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/acid-jazz'},
    { name: 'other', parent: 'other', wiki: '', spotify: '', lastfm: 'https://www.last.fm/tag/other'},
];

export { genres };
